### ISSUE TITLE
MORE_RESULTS_AFTER_LIMIT Erroneously Returned

### ISSUE THREAD

**Issue by bpv** [GoogleCloudPlatform/google-cloud-datastore#48]
When setting a LIMIT in the query, the JSON API always returns 'MORE_RESULTS_AFTER_LIMIT' for the the moreResults property in the response even though there are no more results.

**Comment by zyberspace** [comment]
This issue still exists btw.

At the moment this means always one extra call (with 0 results) to know that there are no more results.

**Comment by pcostell** [comment]
This is now fixed. An important note though: `more_results` will always give you a conservative answer. So it is still possible that `MORE_RESULTS_AFTER_LIMIT` is returned instead of `NO_MORE_RESULTS` if Datastore was unable to determine if there were more results (due to time or workload constraints).

**Comment by zyberspace** [comment]
Sry, for the late answer but i just wanted to change my code to finally use the `NO_MORE_RESULTS` answer and i still get `MORE_RESULTS_AFTER_LIMIT` every time, even if there is just one entity for the specific kind.

Would be great if you maybe have any numbers on what the odds are that Datastore can't determine if there are more results. Because if i need to run another call 90% of the time because Datastore doesn't know if there are more results, there is no reason to change the code to use `NO_MORE_RESULTS`.

Also i should note that i am currently not on a paid plan because the free contingent is enough till the app goes into production. Maybe the "free" Datastore instances are always under heavy workload?

**Comment by pcostell** [comment]
Most of the time `NO_MORE_RESULTS` should be returned. What client library are you using? The results are only correct for clients that use Cloud Datastore API v1beta3. Clients that are still using the v1beta2 API will continue seeing `MORE_RESULTS_AFTER_LIMIT`.

**Comment by zyberspace** [comment]
Ty, updating to v1beta3 fixed it for me.
